version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: wimd-password
      POSTGRES_USER: wimd-admin
      POSTGRES_DB: wimd
    ports:
      - 5432:5432